### ISSUE TITLE
feed does not validate

### ISSUE THREAD

**Issue by letmejustputthishere** [domwoe/rss_canister#1]
Following the link from the readme to validate, an error appears

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fvo3eu-eyaaa-aaaak-qawba-cai.raw.ic0.app%2Ffeed.rss

![E7B8FA76-B97F-4C0E-87E7-8EB0B262DA0C](https://user-images.githubusercontent.com/32162112/195272401-d83de468-c878-4c46-990f-0cea5cf966d1.jpeg)

**Comment by domwoe** [comment]
Thanks! I added the guid field after testing. guid seems to be a URL or at least an URI. I'll update that later.
